#!/usr/bin/env python3
"""Generate src/kenney.ts from Kenney's Input Prompts pack (CC0,
https://kenney.nl/assets/input-prompts): the button icons the plugin uses,
embedded as SVG strings.

    python3 scripts/gen_icons.py /path/to/kenney_input-prompts
"""
import json
import os
import re
import sys

ICONS = {
    "Nintendo Switch 2": [
        "switch_button_a", "switch_button_b", "switch_button_x", "switch_button_y",
        "switch_button_l", "switch_button_r", "switch_button_zl", "switch_button_zr",
        "switch_button_minus", "switch_button_plus", "switch_button_home",
        "switch_button_c", "switch_button_gl", "switch_button_gr", "switch_button_sl", "switch_button_sr",
        "switch_stick_l_press", "switch_stick_r_press",
        "switch_dpad_up", "switch_dpad_down", "switch_dpad_left", "switch_dpad_right",
    ],
    "Xbox Series": [
        "xbox_button_color_a", "xbox_button_color_b", "xbox_button_color_x", "xbox_button_color_y",
        "xbox_lb", "xbox_rb", "xbox_lt", "xbox_rt", "xbox_button_back", "xbox_button_start",
        "xbox_ls", "xbox_rs", "xbox_guide",
        "xbox_dpad_up", "xbox_dpad_down", "xbox_dpad_left", "xbox_dpad_right",
    ],
    "PlayStation Series": [
        "playstation_button_color_cross", "playstation_button_color_circle",
        "playstation_button_color_square", "playstation_button_color_triangle",
        "playstation_trigger_l1", "playstation_trigger_r1", "playstation_trigger_l2", "playstation_trigger_r2",
        "playstation5_button_create", "playstation5_button_options",
        "playstation_button_l3", "playstation_button_r3",
        "playstation5_touchpad_press_center", "playstation5_touchpad_press_left", "playstation5_touchpad_press_right",
        "playstation5_button_mute", "playstation5_elite_lb", "playstation5_elite_rb",
        "playstation5_elite_fn_l", "playstation5_elite_fn_r",
        "playstation_dpad_up", "playstation_dpad_down", "playstation_dpad_left", "playstation_dpad_right",
    ],
    "Steam Deck": [
        "steamdeck_button_l4", "steamdeck_button_r4",
        "steamdeck_button_quickaccess",
    ],
    "Nintendo Gamecube": [
        "gamecube_button_color_a", "gamecube_button_color_b", "gamecube_button_x", "gamecube_button_y",
        "gamecube_button_z", "gamecube_trigger_l", "gamecube_trigger_r", "gamecube_button_start",
        "gamecube_dpad_up", "gamecube_dpad_down", "gamecube_dpad_left", "gamecube_dpad_right",
    ],
}


def minify(svg):
    svg = re.sub(r"<\?xml[^>]*>", "", svg)
    svg = re.sub(r"<defs\s*/>", "", svg)
    svg = re.sub(r">\s+<", "><", svg)
    svg = re.sub(r"\s+", " ", svg)
    return svg.strip()


def main():
    root = sys.argv[1]
    out = {}
    for folder, names in ICONS.items():
        for n in names:
            path = os.path.join(root, folder, "Vector", n + ".svg")
            with open(path, encoding="utf-8") as f:
                svg = minify(f.read())
            if "<script" in svg.lower() or "<foreignobject" in svg.lower():
                sys.exit("unexpected content in " + path)
            out[n] = svg
    dst = os.path.join(os.path.dirname(__file__), "..", "src", "kenney.ts")
    with open(dst, "w", encoding="utf-8") as f:
        f.write("// Generated by scripts/gen_icons.py from Kenney's Input Prompts (CC0, kenney.nl).\n")
        f.write("export const KENNEY: Record<string, string> = ")
        f.write(json.dumps(out, indent=0, sort_keys=True))
        f.write(";\n")
    print("%d icons, %d bytes" % (len(out), os.path.getsize(dst)))


main()
